/*-----------------------------------------------------------------------------
 * TITLE: OEM_BANK4_Func.H
 *
 * Author : Dino
 *
 * Note : These functions are reference only.
 *        Please follow your project software specification to do some modification.
 *---------------------------------------------------------------------------*/
#ifndef OEM_BANK4_Func_H
#define OEM_BANK4_Func_H

extern void Bank4_Test(void);



#endif