/*-----------------------------------------------------------------------------
 * TITLE: OEM_BANK6_Func.H
 *
 * Author : Dino
 *
 * Note : These functions are reference only.
 *        Please follow your project software specification to do some modification.
 *---------------------------------------------------------------------------*/
#ifndef OEM_BANK6_Func_H
#define OEM_BANK6_Func_H

extern void Bank6_Test(void);



#endif